<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB4kjUws\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB4kjUws/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB4kjUws.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB4kjUws\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB4kjUws\App_KernelDevDebugContainer([
    'container.build_hash' => 'B4kjUws',
    'container.build_id' => '2b2fd106',
    'container.build_time' => 1660054384,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB4kjUws');
