<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDPExyNu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDPExyNu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDPExyNu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDPExyNu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDPExyNu\App_KernelDevDebugContainer([
    'container.build_hash' => 'DPExyNu',
    'container.build_id' => '3295d760',
    'container.build_time' => 1659964264,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDPExyNu');
