<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMT0eYO2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMT0eYO2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMT0eYO2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMT0eYO2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMT0eYO2\App_KernelDevDebugContainer([
    'container.build_hash' => 'MT0eYO2',
    'container.build_id' => '6d19010c',
    'container.build_time' => 1659966771,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMT0eYO2');
